# Set the list of files that when modified will trigger GitHub Actions
# (GA) continuous integration (CI) to run

on:
  push:
    paths:
      - 'data/**'
      - 'scripts/**'
  pull_request:
    paths:
      - 'data/**'
      - 'scripts/**'
  workflow_dispatch:
   
# Name the workflow as it will appear on GA status page
name: update_plots

jobs:
  update_plots:
    # Set the operating system CI assumes:
    runs-on: macOS-latest
    
    # Allow only authorized collaborators to trigger GA:
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    # All steps in workflow:
    steps:
      # Housekeeping: Use various GA tools, install R, install pandoc
      # (to be able to use RMarkdown)
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
           
      
      # Housekeeping: Install all packages listed in DESCRIPTION file
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "rmarkdown"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      
      # # Housekeeping: Run package check (may not be needed)
      # - name: Check
      #   run: |
      #     options(crayon.enabled = TRUE)
      #     rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
      #   shell: Rscript {0}
      
      # Create results/full_record_dendroband_plots.png and results/dendroband_plots_July18-24.png
      - name: Prepare and Plot dendrometer data
        id: prepare_data
        run: |
          source("scripts/prepare_data.R")
        shell: Rscript {0}     
        
      # # Create doc/AutoDendrometers_map.jpg THIS DOES NOT WORK AS IT RELIES ON FILES OUTSIDE OF THIS REPO
      # - name: Map of denrometers
      #   id: plot_sampled_trees
      #   run: |
      #     source("scripts/plot_sampled_trees.R")
      #   shell: Rscript {0}


      # Commit and push all new files, assigned to GA bot
      - name: Commit and push all new files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all || echo "No changes to commit"
          git commit -m "Added/modified files and updated README" || echo "No changes to commit"
          git push origin

